from django.urls import path
from django.contrib.auth.views import LogoutView
from . import views

app_name = 'mainapp'

urlpatterns = [
    path('', views.home, name='home'),
    path('products/', views.product_list, name='product_list'),
    path('product/<slug:slug>/', views.product_detail, name='product_detail'),
    path('category/<slug:category_slug>/', views.product_list, name='category_products'),
    path('cart/', views.cart, name='cart'),
    path('cart/add/', views.cart_add, name='cart_add'),
    path('cart/update/', views.cart_update, name='cart_update'),
    path('cart/remove/', views.cart_remove, name='cart_remove'),
    path('cart/update-session/', views.cart_update, name='cart_update_session'),
    path('cart/remove-session/', views.cart_remove, name='cart_remove_session'),
    path('cart/clear/', views.cart_clear, name='cart_clear'),
    path('cart/apply-coupon/', views.apply_coupon, name='apply_coupon'),
    path('checkout/', views.checkout, name='checkout'),
    path('orders/', views.order_list, name='orders'),
    path('order/<int:order_id>/', views.order_detail, name='order_detail'),
    path('payment/paypal/<int:order_id>/', views.paypal_payment, name='paypal_payment'),
    path('payment/telebirr/<int:order_id>/', views.telebirr_payment, name='telebirr_payment'),
    path('payment/notify/', views.payment_notify, name='payment_notify'),
    path('payment/return/', views.payment_return, name='payment_return'),
    path('search/', views.search_products, name='search_products'),
    path('product/<int:product_id>/rate/', views.rate_product, name='rate_product'),
    path('newsletter/subscribe/', views.newsletter_subscribe, name='newsletter_subscribe'),
    path('product/<int:product_id>/review/add/', views.add_review, name='add_review'),
    path('review/<int:review_id>/edit/', views.edit_review, name='edit_review'),
    path('review/<int:review_id>/delete/', views.delete_review, name='delete_review'),
    path('review/<int:review_id>/helpful/', views.mark_review_helpful, name='mark_review_helpful'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
    path('profile/', views.profile, name='profile'),
    path('logout/', LogoutView.as_view(next_page='mainapp:home'), name='logout'),
    path('user/products/', views.user_products, name='user_products'),
    path('user/products/create/', views.create_product, name='create_product'),
    path('user/products/<slug:slug>/edit/', views.edit_product, name='edit_product'),
    path('user/products/<slug:slug>/delete/', views.delete_product, name='delete_product'),
    path('conversations/', views.conversations, name='conversations'),
    path('conversations/<int:conversation_id>/', views.conversation_detail, name='conversation_detail'),
    path('product/<int:product_id>/message/', views.start_conversation, name='start_conversation'),
    path('api/unread-messages/', views.get_unread_message_count, name='unread_messages'),
    path('dashboard/', views.user_dashboard, name='user_dashboard'),
    path('payment/initiate/<int:order_id>/', views.initiate_payment, name='initiate_payment'),
    path('admin-dashboard/', views.admin_dashboard, name='admin_dashboard'),
    path('admin/users/', views.user_list, name='users'),
] 